-- Consultar foreign keys existentes na tabela ordens_trabalho
SELECT 
    CONSTRAINT_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME,
    DELETE_RULE,
    UPDATE_RULE
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
        USING (CONSTRAINT_SCHEMA, CONSTRAINT_NAME)
WHERE 
    TABLE_SCHEMA = 'carrepairshopgest'
    AND TABLE_NAME = 'ordens_trabalho'
    AND REFERENCED_TABLE_NAME IS NOT NULL;
