import type { Metadata } from "next";

/**
 * Força renderização dinâmica para verificar status da aplicação a cada pedido
 * Sem isto, o status seria cacheado em build time
 */
export const dynamic = 'force-dynamic';

import "./globals.css";
import { getAppStatus } from "@/lib/appStatus";
import OfflineGuard from "@/components/OfflineGuard";

/**
 * Metadata para SEO e meta tags
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout - Layout raiz da aplicação
 * 
 * Responsabilidades:
 * 1. Verifica status da aplicação (pago/não pago)
 * 2. Se enabled=true: renderiza app normalmente com OfflineGuard
 * 3. Se enabled=false: mostra mensagem de aplicação desligada
 * 4. Aplica fontes globais e estilos CSS
 * 
 * OfflineGuard monitora conectividade e redireciona para /offline se necessário
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Verifica se aplicação está habilitada (sistema de pagamento)
  const status = await getAppStatus();
  
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {status.enabled ? (
          <>
            {/* Guard que monitora conectividade */}
            <OfflineGuard />
            {children}
          </>
        ) : (
          /* Tela de aplicação desligada por falta de pagamento */
          <div className="min-h-screen bg-gray-900 text-gray-100 flex items-center justify-center px-6">
            <div className="max-w-2xl text-center">
              <h1 className="text-3xl font-bold">Aplicacao desligada</h1>
              <p className="mt-4 text-lg text-gray-300">
                A aplicacao foi desligada devido a falta de pagamento e sera religada
                assim que o pagamento for efetuado.
              </p>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
