import type { Metadata } from "next";
// force dynamic rendering so app status is read on every request
export const dynamic = 'force-dynamic';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getAppStatus } from "@/lib/appStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const status = await getAppStatus();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {status.enabled ? (
          children
        ) : (
          <div className="min-h-screen bg-gray-900 text-gray-100 flex items-center justify-center px-6">
            <div className="max-w-2xl text-center">
              <h1 className="text-3xl font-bold">Aplicacao desligada</h1>
              <p className="mt-4 text-lg text-gray-300">
                A aplicacao foi desligada devido a falta de pagamento e sera religada
                assim que o pagamento for efetuado.
              </p>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
